spring:
  application:
    name: customer-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/customerdb?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:bensadik}
    password: ${JDBC_DATABASE_PASSWORD:asexbs}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
server:
  port: ${PORT:9001}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true